### ISSUE TITLE
Your app contains an intent redirection vulnerability. while publishing to Play store app got rejected.

### ISSUE THREAD

**Issue by SachinCodeMatrix** [pharshdev/sms_user_consent#6]
<img width="1074" alt="Screenshot 2022-02-01 at 7 10 20 PM" src="https://user-images.githubusercontent.com/80881563/151978791-b29137b1-7c3b-433c-a442-24c54c4adef4.png">

**Comment by StolarczykJakub** [comment]
I have this one too. Needs to be addressed fast. Maybe i will try to fix by myself and later on will post the solution.

**Comment by SachinCodeMatrix** [comment]
@StolarczykJakub  we have already fixed the issue. Get the package from this URL

https://github.com/ctnataman/sms_user_consent

**Comment by Kishan-Somaiya** [comment]
Hey @SachinCodeMatrix can you tell me the process how did you solved it ? it'll be really helpful :-)

**Comment by SachinCodeMatrix** [comment]
@Kishan-Somaiya  Just get the package from the  below URL
sms_user_consent:
    git:
      url: https://github.com/ctnataman/sms_user_consent
